# This workflow runs python linting jobs

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
  pull_request:

jobs:
  flake8:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m flake8 $(git ls-files '*.py') --statistics --count

  isort:
    name: Lint with isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m isort $(git ls-files '*.py') --profile black --sl -c --diff

  pydocstyle:
    name: Lint with pydocstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m pydocstyle $(git ls-files '*.py') --count

  bandit:
    name: Security Check with bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m bandit $(git ls-files '*.py') -r -iii -ll

  black:
    name: Lint with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"
      - run: poetry install
      - run: poetry run python -m black $(git ls-files '*.py') --check
