# call to reusable / callable workflows

name: Testing with pytest

on:
  push:
    branches: [main]

jobs:
  call-lint-workflow:
    uses: ./.github/workflows/lint-reusable.yml
    name: Code Quality Check
    with:
      python-version: ${{ vars.PYTHON_VERSION }}

  call-test-workflow:
    name: Run Testing with pytest
    uses: ./.github/workflows/pytest-reusable.yml
    needs: call-lint-workflow
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
