# this workflow runs tests with pytest
# it can be reused by other workflows; see: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
  push:
    branches: [main]

jobs:
  call-lint-workflow:
    uses: ./.github/workflows/lint.yml
    with:
      python-version: ${{ inputs.python-version }}

  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest
